# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20170526_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(max_length=12)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('in_stock', models.BooleanField(default=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('dimensions', models.FloatField(blank=True, null=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Credentials')),
            ],
            options={
                'ordering': ['rating', 'qty', 'date_updated'],
                'verbose_name_plural': 'products',
                'verbose_name': 'product',
            },
        ),
    ]
